<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE target PUBLIC "-//mind.ow2.org//Target Descriptor//EN" "classpath://org/ow2/mind/target/ast/targetDescriptor.dtd">
<target name="Clienti686">
<ldFlag id="dpws_ldPath" value="-L${DPWSCORE_ROOT}/platform/gnu/linux/dpws/i686"/>
<ldFlag id="al_ldPath" value="-L${DPWSCORE_ROOT}/platform/gnu/linux/al/i686"/>
<ldFlag id="dcpl_ldPath" value="-L${DPWSCORE_ROOT}/platform/gnu/linux/dcpl/i686"/>
<ldFlag id="xmltools_ldPath" value="-L${DPWSCORE_ROOT}/platform/gnu/linux/xmltools/i686"/>
<ldFlag id="gsoap_ldPath" value="-L${DPWSCORE_ROOT}/platform/gnu/linux/gsoap-2.7.6/i686"/>
<ldFlag id="common_ldPath" value="-L${DPWSCORE_ROOT}/platform/gnu/linux/common/i686"/>
</target>