$SERVICE_NS_PREFIX$=$NAMESPACE_URI$
xsd__uintsf = #include <stdint.h>| uint64_t | uint64_t*
xsd__int = | int
xsd__long = | long
xsd__string = | char* | char**
xsd__unsignedLong = | unsigned long | unsigned long*
xsd__signedLong = | long long int | long long int*
xsd__unsignedInt = | unsigned int | unsigned int*
xsd__signedInt = | int | int*
xsd__unsignedShort = | unsigned short | unsigned short*
xsd__signedShort = | short int | short int *
xsd__unsignedByte = | unsigned char | unsigned char*
xsd__signedByte = | signed char | signed char*

